### ISSUE TITLE
Bug: converting “works” both ways, incorrectly converting to `px`

### ISSUE THREAD

**Issue by kizu** [ben-eb/postcss-convert-values#10]
If we'd try to minify

``` css
.a{margin:16pc;padding:96in}
```

using this plugin (v1.2.3), we'd get

``` css
.a{margin:1px;padding:1px}
```

It seems that the conversion somehow works both ways, which is, obviously, is not what would be expected.
