### ISSUE TITLE
Bug: case sensitive? (where is my PX bro :)

### ISSUE THREAD

**Issue by dmitrykiselyov** [ben-eb/postcss-convert-values#13]
I discovered the issue  when I used cssnano. 

before
```css
body {
  padding: 20PX;
}
```

after

```css
body {
  padding: 20;
}
```
Why I need px in uppercase? 
Because sometimes I need this https://github.com/cuth/postcss-pxtorem#a-message-about-ignoring-properties

Thank you!
