### ISSUE TITLE
Handle leading zero in rem values

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/postcss-convert-values#2]
```css
.one {
    top: 0.25rem
}
```

Should be:

```css
.one {
    top: .25rem
}
```
